language: python - "2.7"

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - "./miniconda.sh -b"
    - export PATH=/home/travis/miniconda2/bin:$PATH
    - conda update --yes conda
    - sudo rm -rf /dev/shm
    - sudo ln -s /run/shm /dev/shm

install:
  - conda install --yes python="2.7" sphinx scikit-learn matplotlib scipy numpy
  - pip install --user travis-sphinx

script:
  - cp -r doc docs
  - cp -r translate/* docs
  - travis-sphinx build --source=docs/

after_success:
  - travis-sphinx deploy
