branches:
  only:
  - master
  - deploy

language: python - "2.7"

before_install:
    - echo "54.230.142.136 apt.dockerproject.org" | sudo tee -a /etc/hosts
    - wget http://repo.continuum.io/miniconda/Miniconda2-4.1.11-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - "./miniconda.sh -b"
    - export PATH=/home/travis/miniconda2/bin:$PATH
    - sudo rm -rf /dev/shm
    - sudo ln -s /run/shm /dev/shm
    - sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended

install:
  - conda install --yes python="2.7" sphinx scikit-learn matplotlib scipy numpy PIL
  - pip install --user travis-sphinx

cache: conda
script:
  - cp -r translate/* doc
  - cd doc
  - travis-sphinx --source=. --nowarn build
  - cd target/doc/build
  - echo "sklearn.lzjqsdd.com" > CNAME
  - cd ../../..

after_success:
  - travis-sphinx --branches=master,deploy deploy
